// This file is automatically generated.
#include "cssysdef.h"

struct _Bind_aresed_static_plugins_CRYSTAL
{
  _Bind_aresed_static_plugins_CRYSTAL ();
};
namespace { _Bind_aresed_static_plugins_CRYSTAL bind_aresed_static_plugins_CRYSTAL; }

