// This file is automatically generated.
#include "cssysdef.h"

struct _Bind_ares_static_plugins_CRYSTAL
{
  _Bind_ares_static_plugins_CRYSTAL ();
};
namespace { _Bind_ares_static_plugins_CRYSTAL bind_ares_static_plugins_CRYSTAL; }

