// This file is automatically generated.
#include "cssysdef.h"

struct _Bind_ares_static_plugins
{
  _Bind_ares_static_plugins ();
};
namespace { _Bind_ares_static_plugins bind_ares_static_plugins; }

