// This file is automatically generated.
#include "cssysdef.h"

struct _Bind_aresed_static_plugins
{
  _Bind_aresed_static_plugins ();
};
namespace { _Bind_aresed_static_plugins bind_aresed_static_plugins; }

