// This file is automatically generated.
#include "cssysdef.h"

struct CS_IMPORT_SYM _Bind_common_static_plugins_CEL
{
  _Bind_common_static_plugins_CEL ();
};
namespace { _Bind_common_static_plugins_CEL bind_common_static_plugins_CEL; }

