// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_curvemode[] =
"<?xml version=\"1.0\"?>"
"<!-- curvemode.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>ares.editor.modes.curve</name>"
"        <implementation>CurveMode</implementation>"
"        <description>AresEd Curve Editing Mode</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef CurveMode_FACTORY_REGISTER_DEFINED 
  #define CurveMode_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(CurveMode) 
  #endif

class curvemode
{
SCF_REGISTER_STATIC_LIBRARY(curvemode,metainfo_curvemode)
  #ifndef CurveMode_FACTORY_REGISTERED 
  #define CurveMode_FACTORY_REGISTERED 
    CurveMode_StaticInit CurveMode_static_init__; 
  #endif
public:
 curvemode();
};
curvemode::curvemode() {}

}
