// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_dynworld[] =
"<?xml version=\"1.0\"?>"
"<!-- dynworld.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>utility.dynamicworld</name>"
"        <implementation>DynamicWorld</implementation>"
"        <description>Dynamic World Plugin</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef DynamicWorld_FACTORY_REGISTER_DEFINED 
  #define DynamicWorld_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(DynamicWorld) 
  #endif

class dynworld
{
SCF_REGISTER_STATIC_LIBRARY(dynworld,metainfo_dynworld)
  #ifndef DynamicWorld_FACTORY_REGISTERED 
  #define DynamicWorld_FACTORY_REGISTERED 
    DynamicWorld_StaticInit DynamicWorld_static_init__; 
  #endif
public:
 dynworld();
};
dynworld::dynworld() {}

}
