// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_decalmode[] =
"<?xml version=\"1.0\"?>"
"<!-- decalmode.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>ares.editor.modes.decal</name>"
"        <implementation>DecalMode</implementation>"
"        <description>AresEd Decal Editing Mode</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef DecalMode_FACTORY_REGISTER_DEFINED 
  #define DecalMode_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(DecalMode) 
  #endif

class decalmode
{
SCF_REGISTER_STATIC_LIBRARY(decalmode,metainfo_decalmode)
  #ifndef DecalMode_FACTORY_REGISTERED 
  #define DecalMode_FACTORY_REGISTERED 
    DecalMode_StaticInit DecalMode_static_init__; 
  #endif
public:
 decalmode();
};
decalmode::decalmode() {}

}
