// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_dynfacteditor[] =
"<?xml version=\"1.0\"?>"
"<!-- dynfacteditor.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>ares.editor.dynfacteditor</name>"
"        <implementation>DynfactDialog</implementation>"
"        <description>AresEd Dynamic Factory Editor</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef DynfactDialog_FACTORY_REGISTER_DEFINED 
  #define DynfactDialog_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(DynfactDialog) 
  #endif

class dynfacteditor
{
SCF_REGISTER_STATIC_LIBRARY(dynfacteditor,metainfo_dynfacteditor)
  #ifndef DynfactDialog_FACTORY_REGISTERED 
  #define DynfactDialog_FACTORY_REGISTERED 
    DynfactDialog_StaticInit DynfactDialog_static_init__; 
  #endif
public:
 dynfacteditor();
};
dynfacteditor::dynfacteditor() {}

}
