// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_marker[] =
"<?xml version=\"1.0\"?>"
"<!-- marker.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>utility.marker</name>"
"        <implementation>MarkerManager</implementation>"
"        <description>Marker Plugin</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef MarkerManager_FACTORY_REGISTER_DEFINED 
  #define MarkerManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(MarkerManager) 
  #endif

class marker
{
SCF_REGISTER_STATIC_LIBRARY(marker,metainfo_marker)
  #ifndef MarkerManager_FACTORY_REGISTERED 
  #define MarkerManager_FACTORY_REGISTERED 
    MarkerManager_StaticInit MarkerManager_static_init__; 
  #endif
public:
 marker();
};
marker::marker() {}

}
