// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_roommode[] =
"<?xml version=\"1.0\"?>"
"<!-- roommode.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>ares.editor.modes.room</name>"
"        <implementation>RoomMode</implementation>"
"        <description>AresEd Room Editing Mode</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef RoomMode_FACTORY_REGISTER_DEFINED 
  #define RoomMode_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(RoomMode) 
  #endif

class roommode
{
SCF_REGISTER_STATIC_LIBRARY(roommode,metainfo_roommode)
  #ifndef RoomMode_FACTORY_REGISTERED 
  #define RoomMode_FACTORY_REGISTERED 
    RoomMode_StaticInit RoomMode_static_init__; 
  #endif
public:
 roommode();
};
roommode::roommode() {}

}
